trigger:
  branches:
    include:
      - main

# Define pipeline parameters for environment selection
parameters:
  - name: environment
    displayName: "Select Environment"
    type: string
    default: "dev"
    values:
      - dev
      - staging
      - prod

stages:
  - stage: Init
    displayName: "Terraform Init Stage"
    jobs:
      - job: Init
        displayName: "Initialize Terraform for $(environment)"
        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
          - task: UseAzureCLI@2
            inputs:
              azureSubscription: 'your-azure-subscription'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Set environment-specific backend config and var files
                if [[ "${{ parameters.environment }}" == "dev" ]]; then
                  BACKEND_CONFIG_FILE="backend-config-dev.conf"
                elif [[ "${{ parameters.environment }}" == "staging" ]]; then
                  BACKEND_CONFIG_FILE="backend-config-staging.conf"
                elif [[ "${{ parameters.environment }}" == "prod" ]]; then
                  BACKEND_CONFIG_FILE="backend-config-prod.conf"
                else
                  echo "Invalid environment selected"
                  exit 1
                fi

                # Initialize Terraform with the selected backend config
                terraform init -backend-config=$BACKEND_CONFIG_FILE

  - stage: Plan
    displayName: "Terraform Plan Stage"
    dependsOn: Init
    jobs:
      - job: Plan
        displayName: "Plan Terraform for $(environment)"
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: UseAzureCLI@2
            inputs:
              azureSubscription: 'your-azure-subscription'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Select environment-specific tfvars file
                if [[ "${{ parameters.environment }}" == "dev" ]]; then
                  TFVARS_FILE="dev.tfvars"
                elif [[ "${{ parameters.environment }}" == "staging" ]]; then
                  TFVARS_FILE="staging.tfvars"
                elif [[ "${{ parameters.environment }}" == "prod" ]]; then
                  TFVARS_FILE="prod.tfvars"
                else
                  echo "Invalid environment selected"
                  exit 1
                fi

                # Run Terraform plan
                terraform plan -var-file=$TFVARS_FILE -out=tfplan

          # Publish the Terraform plan as an artifact for review
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: tfplan
              artifactName: tfplan
              publishLocation: "pipeline"

  - stage: Apply
    displayName: "Terraform Apply Stage"
    dependsOn: Plan
    variables:
      KV_NAME: "my-${{ parameters.environment }}-keyvault" # Reuse the Key Vault name in this stage
    jobs:
      - deployment: Apply
        displayName: "Apply Terraform for $(environment)"
        environment: "$(environment)"
        pool:
          vmImage: 'ubuntu-latest'
        
        # Manual approval step before the apply job
        strategy:
          runOnce:
            preDeploy:
              - task: ManualValidation@0
                inputs:
                  instructions: "Please review the Terraform plan before approving deployment to $(environment)"
                  onTimeout: "reject"
                  timeout: "30"  # Timeout for approval in minutes

            deploy:
              steps:
                - task: UseAzureCLI@2
                  inputs:
                    azureSubscription: 'your-azure-subscription'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      # Apply the previously approved Terraform plan
                      terraform apply -auto-approve tfplan
                      # Capture Terraform Outputs
                      echo "##vso[task.setvariable variable=ACR_LOGIN_SERVER;isOutput=true]$(terraform output -raw acr_login_server)"
                      echo "##vso[task.setvariable variable=POSTGRES_HOST;isOutput=true]$(terraform output -raw postgresql_host)"
                      echo "##vso[task.setvariable variable=POSTGRES_DB;isOutput=true]$(terraform output -raw postgresql_database)"
                      echo "##vso[task.setvariable variable=POSTGRES_USER;isOutput=true]$(terraform output -raw postgresql_username)"
                      echo "##vso[task.setvariable variable=POSTGRES_PASSWORD;isOutput=true]$(terraform output -raw postgresql_password)"


  - stage: StoreSecrets
      displayName: "Store Secrets in Key Vault for ${{ parameters.environment }}"
      dependsOn: ApplyInfrastructure
      variables:
        KV_NAME: "my-${{ parameters.environment }}-keyvault" # Reuse the Key Vault name in this stage
      jobs:
        - job: StoreSecretsJob
          displayName: "Store Secrets for ${{ parameters.environment }}"
          steps:
           # Step to Store Secrets in Key Vault
            - task: UseAzureCLI@2
              inputs:
                azureSubscription: 'your-azure-subscription'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  echo "Storing secrets in Key Vault: $(KV_NAME)"
                  az keyvault secret set --vault-name $(KV_NAME) --name "${{ parameters.environment }}-ACR-Login-Server" --value "$(ACR_LOGIN_SERVER)"
                  az keyvault secret set --vault-name $(KV_NAME) --name "${{ parameters.environment }}-Postgres-Host" --value "$(POSTGRES_HOST)"
                  az keyvault secret set --vault-name $(KV_NAME) --name "${{ parameters.environment }}-Postgres-DB" --value "$(POSTGRES_DB)"
                  az keyvault secret set --vault-name $(KV_NAME) --name "${{ parameters.environment }}-Postgres-User" --value "$(POSTGRES_USER)"
                  az keyvault secret set --vault-name $(KV_NAME) --name "${{ parameters.environment }}-Postgres-Password" --value "$(POSTGRES_PASSWORD)"


