trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '1.0.0'
  - script: |
      terraform init
      terraform apply -auto-approve
    displayName: 'Terraform Init and Apply'
